//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renting.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/RentCar.Model")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRent", Namespace="http://schemas.datacontract.org/2004/07/RentCar.Model")]
    [System.SerializableAttribute()]
    public partial class CarRent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Renting.ServiceReference1.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PricePerHourField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Renting.ServiceReference1.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerHour {
            get {
                return this.PricePerHourField;
            }
            set {
                if ((this.PricePerHourField.Equals(value) != true)) {
                    this.PricePerHourField = value;
                    this.RaisePropertyChanged("PricePerHour");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceRent")]
    public interface IServiceRent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/getCars", ReplyAction="http://tempuri.org/IServiceRent/getCarsResponse")]
        Renting.ServiceReference1.Car[] getCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/getCars", ReplyAction="http://tempuri.org/IServiceRent/getCarsResponse")]
        System.Threading.Tasks.Task<Renting.ServiceReference1.Car[]> getCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/getCarReservations", ReplyAction="http://tempuri.org/IServiceRent/getCarReservationsResponse")]
        Renting.ServiceReference1.CarRent[] getCarReservations(Renting.ServiceReference1.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/getCarReservations", ReplyAction="http://tempuri.org/IServiceRent/getCarReservationsResponse")]
        System.Threading.Tasks.Task<Renting.ServiceReference1.CarRent[]> getCarReservationsAsync(Renting.ServiceReference1.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/calculateCost", ReplyAction="http://tempuri.org/IServiceRent/calculateCostResponse")]
        decimal calculateCost(Renting.ServiceReference1.CarRent carRent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/calculateCost", ReplyAction="http://tempuri.org/IServiceRent/calculateCostResponse")]
        System.Threading.Tasks.Task<decimal> calculateCostAsync(Renting.ServiceReference1.CarRent carRent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRentChannel : Renting.ServiceReference1.IServiceRent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRentClient : System.ServiceModel.ClientBase<Renting.ServiceReference1.IServiceRent>, Renting.ServiceReference1.IServiceRent {
        
        public ServiceRentClient() {
        }
        
        public ServiceRentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Renting.ServiceReference1.Car[] getCars() {
            return base.Channel.getCars();
        }
        
        public System.Threading.Tasks.Task<Renting.ServiceReference1.Car[]> getCarsAsync() {
            return base.Channel.getCarsAsync();
        }
        
        public Renting.ServiceReference1.CarRent[] getCarReservations(Renting.ServiceReference1.Car car) {
            return base.Channel.getCarReservations(car);
        }
        
        public System.Threading.Tasks.Task<Renting.ServiceReference1.CarRent[]> getCarReservationsAsync(Renting.ServiceReference1.Car car) {
            return base.Channel.getCarReservationsAsync(car);
        }
        
        public decimal calculateCost(Renting.ServiceReference1.CarRent carRent) {
            return base.Channel.calculateCost(carRent);
        }
        
        public System.Threading.Tasks.Task<decimal> calculateCostAsync(Renting.ServiceReference1.CarRent carRent) {
            return base.Channel.calculateCostAsync(carRent);
        }
    }
}
